name: Build and Release

on:
  # push:
   #   tags:        
   #      - '*'
   push:
     branches: [ main ]
     paths-ignore:
       - create-release.yml
       - update-release.yml

env:
  IMAGE_NAME: eche21/app
  GITHUB_REF_NAME: ${{ github.ref_name }}

jobs:
  #  Build-Linux:
  #    runs-on: ubuntu-latest
  #    steps:
  #    - uses: actions/checkout@v3
  #    - name: Docker Login
  #      uses: docker/login-action@v1.14.1
  #      with:
  #        username: ${{ secrets.DOCKER_USER }}
  #        password: ${{ secrets.DOCKER_PASSWORD }}
  #    - name: Build and push app to Dockerhub
  #      uses: docker/build-push-action@v2.10.0
  #      with:
  #        context: './app'
  #        file: 'app/Dockerfile'
  #        push: true
  #        tags: ${{ env.IMAGE_NAME }}:${{ env.GITHUB_REF_NAME }}
   build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false 
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        with:
          package-dir: './package.json'
          # from-tag: v0.4
          # to-tag: v0.6
