# name: Build and Release

# on:
#   # push:
#   #   tags:        
#   #      - '*'
#   push:
#     branches: [ main ]
#     paths-ignore:
#       - create-release.yml
#       - update-release.yml

# env:
#   IMAGE_NAME: eche21/app
#   GITHUB_REF_NAME: ${{ github.ref_name }}

# jobs:
#   Build-Linux:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Docker Login
#       uses: docker/login-action@v1.14.1
#       with:
#         username: ${{ secrets.DOCKER_USER }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
#     - name: Build and push app to Dockerhub
#       uses: docker/build-push-action@v2.10.0
#       with:
#         context: './app'
#         file: 'app/Dockerfile'
#         push: true
#         tags: ${{ env.IMAGE_NAME }}:${{ env.GITHUB_REF_NAME }}
    # - name: Changelog
    #   uses: scottbrenner/generate-changelog-action@master
    #   id: Changelog
    #   with:
    #     package-dir: './app/package.json'
    #     from-tag: v0.4
    #     to-tag: v0.6
name: 'CI'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@{latest-release}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}